### ISSUE TITLE
Grain Size Header Scale Misaligned in Lithology Track PSICAT 1.2.0

### ISSUE THREAD

**Issue by jllancaster** [laccore/coretools#11]
When checking the "Grain Size Header" option for the Lithology Track in PISCAT 1.2.0, the scale appears to be misaligned with the width of the lithology column, as set by the grain size column.

![image](https://github.com/user-attachments/assets/91acc875-70da-4298-a588-8f7c57591e3a)

**Comment by sorghumking** [comment]
You are correct! This is one of many rough edges in the 1.2.0 release which will receive further attention in the coming months. The misalignment is due to a mismatch between the options in the Grain Size column and PSICAT's Grain Size Scale, which can be viewed from the Edit > Grain Size Scale... menu item.

Assuming you'd like the Grain Size Header in the Lithology column to display names that correspond to the options available in the Grain Size column, copy/paste the following string into the Edit > Grain Size Scale... text field:

0.2:0<Clay<1<Silty Clay<2<Sandy Clay<3<Silt<4<Very Fine Sand<5<Fine Sand<6<Medium Sand<7<Coarse Sand<8<Very Coarse Sand<9<Granule<10<Pebble<11<Cobble<12<Boulder<13

Click OK, and the header should redraw and resolve the misalignment you're observing.

The value "0.2" at the beginning of this unwieldy string indicates the minimum width to draw a Lithology interval for which no Grain Size has been defined. This value represents a percentage of the total Lithology Column width. 0.2, or 20%, is the default. 0.5 would fill 50% of the column. 0 would fill 0%, 1 would fill 100%. (Both would be odd choices, but they are technically valid!)

In any event, modify that value to your liking.

Among the many plans for future releases is to wrap this goofy string in a user-friendly interface for modifying the Grain Size Scale, especially given its strong tie to the Grain Size column options.

If you want to delve into this and e.g. modify the default Grain Size options, get in touch with me (Brian G) at the email address listed here - https://cse.umn.edu/csd/our-team - and we can talk through things. The changes in 1.2.0 have rendered many of our video tutorials obsolete, so for the time being, email/Zoom is the best way to get folks up to speed.

Thanks for reporting this bug, and for your interest in PSICAT!

**Comment by jllancaster** [comment]
Hey that did it! Thank you very much. Really appreciate the in-depth explanation and help. Its a great program and really appreciated.
